name: Update public website

on:
  push:
    branches: ["main"]

jobs:
  publish:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Generate public website
        run: |
          npm ci
          npm run build:web

      - name: Publish current workdir (which contains generated content) to GitHub Pages
        uses: rayluo/github-pages-overwriter@v1.3
        with:
          source-directory: www
          target-branch: gh-pages
